!
frr version 8.4_git
frr defaults traditional
hostname r5
domainname localdomain
no ipv6 forwarding
!
router ospf
 ospf router-id 5.5.5.5
 network 10.0.15.0/30 area 0
 network 10.0.35.0/30 area 0
 network 10.0.45.0/30 area 0
 network 192.168.50.0/24 area 0
exit
!
end
