!
frr version 8.4_git
frr defaults traditional
hostname r4
domainname localdomain
no ipv6 forwarding
!
router ospf
 ospf router-id 4.4.4.4
 network 10.0.34.0/30 area 0
 network 10.0.45.0/30 area 0
exit
!
end
